In [1]:
import itertools
import pandas as pd
import numpy as np

wcsData = pd.read_csv('wcsDataLong.csv')
wcsData.head()

,Unnamed: 0,language,speaker,chipID,chipRow,chipColumn,term,cieL,cieA,cieB,srgbR,srgbG,srgbB
0,1,1,1,1,E,29,LB,61.70,-4.52,-39.18,78.57825,154.92015,217.98420
1,2,1,1,2,C,23,LB,81.35,-19.64,-4.30,154.21380,213.16215,209.42385
2,3,1,1,3,F,4,LE,51.57,55.20,68.32,219.04245,71.68815,0.00000
3,4,1,1,4,I,36,WK,20.54,24.14,-14.33,73.76640,35.22825,70.83390
4,5,1,1,5,C,20,LF,81.35,-33.04,4.96,130.28205,218.97615,191.75745

In [ ]:
all_pairs = pd.DataFrame() 

for k in range(1, max(wcsData['language'])+1):
    lnk = wcsData[(wcsData['language'] == k)]

    for j in range(1, max(lnk['speaker'])+1):

        lnkspkj = lnk[(lnk['speaker'] == j)]
        lnkspkj.index = range(0,330)


        pairs = pd.DataFrame(itertools.combinations(range(1,331), 2))
        pairs = pairs.rename(columns={0:"chipID1", 1:"chipID2"})
        pairs['same'] = np.zeros(len(pairs.index), dtype=int)
        pairs['language'] = k
        pairs['speaker'] = j

        for i in range(len(pairs.index)):

            chip1 = pairs['chipID1'][i]
            chip2 = pairs['chipID2'][i]

            term1 = lnkspkj[lnkspkj['chipID'] == chip1]['term'][chip1-1]
            term2 = lnkspkj[lnkspkj['chipID'] == chip2]['term'][chip2-1]

            if term1 == term2:
                pairs.iat[i, 2] = 1

        all_pairs = pd.concat([all_pairs, pairs])
        
all_pairs.to_csv('pairs.csv', index=False)